"""Per-language string tables used by the PDF reports.

Phase 4 of the improvement plan moved this dict out of the giant
``reports.py`` so the rendering modules stay focused on layout. The
shape and keys match the legacy table byte-for-byte, so existing
report code (and any external consumer that imported
``REPORT_STRINGS``) keeps working unchanged.
"""

from __future__ import annotations

from typing import Final

REPORT_STRINGS: Final[dict[str, dict[str, str]]] = {
    'en': {
        'agreement_title': "Medical Equipment Loan Agreement",
        'date': "Date",
        'loan_id': "Loan ID",
        'borrower_info': "Borrower Information",
        'name': "Name",
        'id_number': "ID Number",
        'primary_phone': "Primary Phone",
        'secondary_phone': "Secondary Phone",
        'address': "Address",
        'equipment_info': "Equipment Information",
        'equipment_name': "Equipment Name",
        'serial_number': "Serial Number",
        'description': "Description",
        'financial_info': "Financial Information",
        'deposit_amount': "Deposit Amount",
        'donation': "Donation",
        'terms_title': "Terms and Conditions",
        'term1': "1. The borrower agrees to return the equipment in good condition.",
        'term2': "2. The deposit will be refunded upon return of the equipment.",
        'term3': "3. The borrower is responsible for any damage to the equipment.",
        'term4': "4. The equipment must be returned within a reasonable timeframe.",
        'borrower_sig': "Borrower Signature",
        'staff_sig': "Staff Signature",
        'footer1': "Thank you for using our medical equipment loan service",
        'footer2': "",
        'inventory_report_title': "Full Inventory Report",
        'generated_on': "Generated on",
        'header_eq_name': "Equipment Name",
        'header_total': "Total",
        'header_in_stock': "In Stock",
        'header_on_loan': "On Loan",
        'header_deposit': "Deposit",
        'total_row': "TOTAL",
        'loans_report_title': "Equipment on Loan Report",
        'total_active_loans': "Total Active Loans",
        'no_active_loans': "No active loans at this time.",
        'header_serial': "Serial No.",
        'header_borrower': "Borrower",
        'header_phone': "Phone",
        'header_loan_date': "Loan Date",
        'header_not_returned': "Not Returned",
        'header_lost': "Lost/Retired",
        'lost_report_title': "Lost / Retired Equipment",
        'header_date_added': "Date Added",
    },
    'he': {
        'agreement_title': "הסכם השאלת ציוד רפואי",
        'date': "תאריך",
        'loan_id': "מספר השאלה",
        'borrower_info': "פרטי השואל",
        'name': "שם",
        'id_number': "תעודת זהות",
        'primary_phone': "טלפון ראשי",
        'secondary_phone': "טלפון משני",
        'address': "כתובת",
        'equipment_info': "פרטי הציוד",
        'equipment_name': "שם הציוד",
        'serial_number': "מספר סידורי",
        'description': "תיאור",
        'financial_info': "פרטים כספיים",
        'deposit_amount': "פיקדון",
        'donation': "תרומה",
        'terms_title': "תנאים",
        'term1': "1. השואל מתחייב להחזיר את הציוד במצב תקין.",
        'term2': "2. הפיקדון יוחזר עם החזרת הציוד.",
        'term3': "3. השואל אחראי לכל נזק שייגרם לציוד.",
        'term4': "4. יש להחזיר את הציוד תוך זמן סביר.",
        'borrower_sig': "חתימת השואל",
        'staff_sig': "חתימת הצוות",
        'footer1': "תודה על השימוש בשירות השאלת הציוד הרפואי שלנו",
        'footer2': "",
        'inventory_report_title': "דוח מלאי מלא",
        'generated_on': "הופק בתאריך",
        'header_eq_name': "שם ציוד",
        'header_total': "סה\"כ",
        'header_in_stock': "במלאי",
        'header_on_loan': "בהשאלה",
        'header_deposit': "פיקדון",
        'total_row': "סה\"כ",
        'loans_report_title': "דוח ציוד בהשאלה",
        'total_active_loans': "סה\"כ השאלות פעילות",
        'no_active_loans': "אין השאלות פעילות כרגע.",
        'header_serial': "מספר סידורי",
        'header_borrower': "שואל",
        'header_phone': "טלפון",
        'header_loan_date': "תאריך השאלה",
        'header_not_returned': "לא הוחזר",
        'header_lost': "אבד/יצא משימוש",
        'lost_report_title': "ציוד שאבד / יצא משימוש",
        'header_date_added': "תאריך הוספה",
    },
    'ar': {
        'agreement_title': "اتفاقية إعارة معدات طبية",
        'date': "التاريخ",
        'loan_id': "رقم الإعارة",
        'borrower_info': "بيانات المستعير",
        'name': "الاسم",
        'id_number': "رقم الهوية",
        'primary_phone': "الهاتف الأساسي",
        'secondary_phone': "هاتف ثانوي",
        'address': "العنوان",
        'equipment_info': "بيانات المعدات",
        'equipment_name': "اسم المعدة",
        'serial_number': "الرقم التسلسلي",
        'description': "الوصف",
        'financial_info': "بيانات مالية",
        'deposit_amount': "مبلغ التأمين",
        'donation': "تبرع",
        'terms_title': "الشروط والأحكام",
        'term1': "1. يوافق المستعير على إعادة المعدات بحالة جيدة.",
        'term2': "2. سيتم رد مبلغ التأمين عند إعادة المعدات.",
        'term3': "3. المستعير مسؤول عن أي ضرر يلحق بالمعدات.",
        'term4': "4. يجب إعادة المعدات في غضون فترة زمنية معقولة.",
        'borrower_sig': "توقيع المستعير",
        'staff_sig': "توقيع الموظف",
        'footer1': "شكرًا لاستخدام خدمتنا لإعارة المعدات الطبية",
        'footer2': "",
        'inventory_report_title': "تقرير المخزون الكامل",
        'generated_on': "أُصدر في",
        'header_eq_name': "اسم المعدة",
        'header_total': "المجموع",
        'header_in_stock': "في المخزن",
        'header_on_loan': "مُعارة",
        'header_deposit': "التأمين",
        'total_row': "المجموع",
        'loans_report_title': "تقرير المعدات المُعارة",
        'total_active_loans': "مجموع الإعارات النشطة",
        'no_active_loans': "لا توجد إعارات نشطة حاليًا.",
        'header_serial': "الرقم التسلسلي",
        'header_borrower': "المستعير",
        'header_phone': "الهاتف",
        'header_loan_date': "تاريخ الإعارة",
        'header_not_returned': "لم يُرجع",
        'header_lost': "مفقود/تالف",
        'lost_report_title': "معدات مفقودة / تالفة",
        'header_date_added': "تاريخ الإضافة",
    },
}


def get_strings(lang: str) -> dict[str, str]:
    """Return the string table for ``lang`` (falls back to English)."""
    return REPORT_STRINGS.get(lang, REPORT_STRINGS['en'])
